language: python
python:
  - "2.7"
before_install:
  - cd ..
  - curl -O http://downloads.sourceforge.net/project/pyqt/PyQt4/PyQt-4.10.1/PyQt-x11-gpl-4.10.1.tar.gz?r=http%3A%2F%2Fwww.riverbankcomputing.co.uk%2Fsoftware%2Fpyqt%2Fdownload&ts=1368089507&use_mirror=garr
  - tar -xvf PyQt-x11-gpl-4.10.1.gz
  - cd PyQt-x11-gpl-4.9.4
  - python configure.py --confirm-license
  - make -j 4
  - sudo make install
  - cd ../MudMapper
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to run tests
script: make test