language: python
python:
  - "2.7"
before_install:
  - cd make/ci
  - ./before_install.sh
  - cd ../..

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to run tests
script: make test